// Demo katalog verisi. Markalar kurgusaldır; gerçek ürün içerikleri admin panelinden girilmelidir.

const img = (name: string) => `/images/demo/${name}.jpg`;

export type SeedCategory = {
  name: string;
  slug: string;
  tagline?: string;
  description?: string;
  image?: string;
  isPopular?: boolean;
  popularLabel?: string;
  isHomeFeatured?: boolean;
  homeSortOrder?: number;
  attributes?: string[];
  children: { name: string; slug: string; image?: string; isPopular?: boolean; popularLabel?: string; homeSortOrder?: number }[];
};

export const CATEGORIES: SeedCategory[] = [
  {
    name: "Bebek Arabaları",
    slug: "bebek-arabalari",
    tagline: "Bebeğinizle her yolculuk daha konforlu.",
    description:
      "Travel sistemden kabin boy modellere, ikiz bebek arabalarından baston arabalara kadar farklı yaşam tarzlarına uygun bebek arabası seçkimizi inceleyin. Katlanma ölçüsü, ağırlık ve süspansiyon gibi detaylarda mağazamızdan birebir destek alabilirsiniz.",
    image: img("hero-stroller"),
    isPopular: true,
    popularLabel: "Bebek Arabası",
    isHomeFeatured: true,
    homeSortOrder: 1,
    attributes: ["type", "age", "capacity", "color"],
    children: [
      { name: "Travel Sistem Bebek Arabaları", slug: "travel-sistem-bebek-arabalari", image: img("p-travel-stroller") },
      { name: "Kabin Boy Bebek Arabaları", slug: "kabin-boy-bebek-arabalari", image: img("p-cabin-stroller") },
      { name: "Baston Bebek Arabaları", slug: "baston-bebek-arabalari", image: img("p-cabin-stroller") },
      { name: "İkiz & Kardeş Bebek Arabaları", slug: "ikiz-kardes-bebek-arabalari", image: img("p-twin-stroller") },
      { name: "Çift Yönlü Bebek Arabaları", slug: "cift-yonlu-bebek-arabalari", image: img("hero-stroller") },
      { name: "Portbebeler", slug: "portbebeler", image: img("p-travel-stroller") },
      { name: "Bebek Arabası Aksesuarları", slug: "bebek-arabasi-aksesuarlari" },
    ],
  },
  {
    name: "Oto Koltukları",
    slug: "oto-koltuklari",
    tagline: "Her yolculukta güvenli ve konforlu.",
    description:
      "Yenidoğandan okul çağına kadar kilo ve boy gruplarına uygun oto koltukları. i-Size ve ISOFIX uyumlu modelleri karşılaştırın, aracınıza uygunluk için bize danışın.",
    image: img("cat-car-seat"),
    isPopular: true,
    popularLabel: "Oto Koltuğu",
    isHomeFeatured: true,
    homeSortOrder: 4,
    attributes: ["weight", "age", "isize", "isofix", "rotation", "color"],
    children: [
      { name: "0–13 kg Oto Koltukları", slug: "0-13-kg-oto-koltuklari", image: img("p-infant-carrier") },
      { name: "0–18 kg Oto Koltukları", slug: "0-18-kg-oto-koltuklari" },
      { name: "9–18 kg Oto Koltukları", slug: "9-18-kg-oto-koltuklari" },
      { name: "9–36 kg Oto Koltukları", slug: "9-36-kg-oto-koltuklari", image: img("cat-car-seat") },
      { name: "0–36 kg Oto Koltukları", slug: "0-36-kg-oto-koltuklari", image: img("p-car-seat-360") },
      { name: "i-Size Oto Koltukları", slug: "i-size-oto-koltuklari" },
      { name: "Booster / Yükseltici", slug: "booster-yukseltici" },
    ],
  },
  {
    name: "Bebek Odası & Mobilya",
    slug: "bebek-odalari",
    tagline: "Tatlı rüyalar için huzurlu odalar.",
    description:
      "Bebek odası takımları, beşikler, anne yanı beşikler, şifonyer ve dolaplar. Oda ölçünüze ve dekorasyonunuza uygun mobilyaları mağazamızda kurulu halde inceleyebilirsiniz.",
    image: img("hero-nursery"),
    isPopular: true,
    popularLabel: "Beşik",
    isHomeFeatured: true,
    homeSortOrder: 2,
    attributes: ["set", "color", "material", "size"],
    children: [
      { name: "Bebek Odası Takımları", slug: "bebek-odasi-takimlari", image: img("p-nursery-set-white") },
      { name: "Beşikler", slug: "besikler", image: img("p-crib") },
      { name: "Anne Yanı Beşikler", slug: "anne-yani-besikler", image: img("p-bedside-crib") },
      { name: "Büyüyen Beşikler", slug: "buyuyen-besikler" },
      { name: "Montessori Yataklar", slug: "montessori-yataklar" },
      { name: "Karyolalar", slug: "karyolalar" },
      { name: "Dolaplar", slug: "dolaplar" },
      { name: "Şifonyerler", slug: "sifonyerler" },
      { name: "Komodinler", slug: "komodinler" },
      { name: "Kitaplıklar", slug: "kitapliklar" },
      { name: "Çalışma Masaları", slug: "calisma-masalari" },
    ],
  },
  {
    name: "Uyku & Konfor",
    slug: "uyku-konfor",
    tagline: "Huzurlu uykular için yumuşak dokunuşlar.",
    description: "Park beşikler, oyun parkları, yataklar ve uyku setleri ile bebeğiniz için güvenli ve konforlu uyku alanları oluşturun.",
    image: img("cat-sleep"),
    isPopular: true,
    popularLabel: "Park Yatak",
    isHomeFeatured: true,
    homeSortOrder: 5,
    attributes: ["age", "color"],
    children: [
      { name: "Park Beşik", slug: "park-besik", image: img("cat-sleep") },
      { name: "Oyun Parkı", slug: "oyun-parki" },
      { name: "Yatak", slug: "yatak" },
      { name: "Uyku Setleri", slug: "uyku-setleri", image: img("cat-textile") },
      { name: "Nevresim", slug: "nevresim" },
      { name: "Battaniye", slug: "battaniye" },
      { name: "Bebek Yastıkları", slug: "bebek-yastiklari" },
    ],
  },
  {
    name: "Beslenme",
    slug: "beslenme",
    tagline: "Mama saatleri daha keyifli.",
    description: "Mama sandalyeleri, biberonlar, emzikler, mama setleri ve sterilizatörler. Ek gıdaya geçişten bağımsız yemeye kadar her döneme uygun ürünler.",
    image: img("cat-feeding"),
    isPopular: true,
    popularLabel: "Mama Sandalyesi",
    isHomeFeatured: true,
    homeSortOrder: 3,
    attributes: ["age", "color"],
    children: [
      { name: "Mama Sandalyeleri", slug: "mama-sandalyeleri", image: img("cat-feeding") },
      { name: "Biberon", slug: "biberon", image: img("p-bottles") },
      { name: "Emzik", slug: "emzik" },
      { name: "Mama Setleri", slug: "mama-setleri" },
      { name: "Tabak & Kaşık", slug: "tabak-kasik" },
      { name: "Suluk", slug: "suluk" },
      { name: "Termos", slug: "termos" },
      { name: "Biberon Isıtıcı", slug: "biberon-isitici" },
      { name: "Sterilizatör", slug: "sterilizator" },
    ],
  },
  {
    name: "Anne & Bebek Bakım",
    slug: "anne-bebek-bakim",
    tagline: "Anne ve bebek için özenli bakım.",
    description: "Göğüs pompaları, bebek bakım setleri, ateş ölçerler, bebek telsizleri ve kameralar ile ilk günlerden itibaren yanınızdayız.",
    image: img("cat-care-bath"),
    isPopular: true,
    popularLabel: "Bakım",
    attributes: ["age", "color"],
    children: [
      { name: "Göğüs Pompaları", slug: "gogus-pompalari" },
      { name: "Anne Bakım Ürünleri", slug: "anne-bakim-urunleri" },
      { name: "Bebek Bakım Setleri", slug: "bebek-bakim-setleri", image: img("cat-care-bath") },
      { name: "Tırnak Bakım", slug: "tirnak-bakim" },
      { name: "Ateş Ölçer", slug: "ates-olcer" },
      { name: "Burun Aspiratörü", slug: "burun-aspiratoru" },
      { name: "Bebek Telsizi", slug: "bebek-telsizi", image: img("p-baby-monitor") },
      { name: "Bebek Kamerası", slug: "bebek-kamerasi" },
    ],
  },
  {
    name: "Banyo & Hijyen",
    slug: "banyo-hijyen",
    tagline: "Banyo zamanı, keyif zamanı.",
    description: "Bebek küvetleri, banyo setleri, havlular, alt açma ürünleri ve tuvalet eğitimi ürünleri.",
    image: img("cat-care-bath"),
    attributes: ["age", "color"],
    children: [
      { name: "Bebek Küvetleri", slug: "bebek-kuvetleri", image: img("cat-care-bath") },
      { name: "Banyo Setleri", slug: "banyo-setleri" },
      { name: "Havlular", slug: "havlular" },
      { name: "Alt Açma Ürünleri", slug: "alt-acma-urunleri" },
      { name: "Lazımlık", slug: "lazimlik" },
      { name: "Tuvalet Eğitim Ürünleri", slug: "tuvalet-egitim-urunleri" },
    ],
  },
  {
    name: "Ev & Yaşam",
    slug: "ev-yasam",
    tagline: "Evin her köşesinde bebek konforu.",
    description: "Ana kucakları, salıncaklar, oyun halıları, aktivite merkezleri ve yürüteçler.",
    image: img("cat-home-living"),
    isPopular: true,
    popularLabel: "Ana Kucağı",
    attributes: ["age", "color"],
    children: [
      { name: "Ana Kucağı", slug: "ana-kucagi", image: img("cat-home-living") },
      { name: "Salıncak", slug: "salincak" },
      { name: "Ev Tipi Ana Kucağı", slug: "ev-tipi-ana-kucagi" },
      { name: "Oyun Halıları", slug: "oyun-halilari" },
      { name: "Aktivite Merkezleri", slug: "aktivite-merkezleri" },
      { name: "Yürüteçler", slug: "yurutecler" },
    ],
  },
  {
    name: "Oyuncak",
    slug: "oyuncak",
    tagline: "Merakı besleyen, doğal oyuncaklar.",
    description: "Eğitici, ahşap ve aktivite oyuncakları ile peluşlar. Yaş grubuna uygun, güvenli ve kaliteli oyuncak seçkisi.",
    image: img("cat-toys"),
    isPopular: true,
    popularLabel: "Oyuncak",
    isHomeFeatured: true,
    homeSortOrder: 6,
    attributes: ["age", "color"],
    children: [
      { name: "Eğitici Oyuncaklar", slug: "egitici-oyuncaklar", image: img("cat-toys") },
      { name: "Ahşap Oyuncaklar", slug: "ahsap-oyuncaklar" },
      { name: "Aktivite Oyuncakları", slug: "aktivite-oyuncaklari" },
      { name: "Peluş Oyuncaklar", slug: "pelus-oyuncaklar", image: img("p-plush") },
      { name: "İlk Oyuncaklar", slug: "ilk-oyuncaklar" },
      { name: "Bebek Jimnastik Ürünleri", slug: "bebek-jimnastik-urunleri" },
    ],
  },
  {
    name: "Dışarı & Seyahat",
    slug: "disari-seyahat",
    tagline: "Keşfe çıkmaya hazır.",
    description: "Bebek bisikletleri, scooterlar, taşıma çantaları ve seyahat yatakları ile her yolculuğa hazır olun.",
    image: img("cat-outdoor"),
    isPopular: true,
    popularLabel: "Bisiklet",
    attributes: ["age", "color"],
    children: [
      { name: "Bebek Bisikletleri", slug: "bebek-bisikletleri", image: img("cat-outdoor") },
      { name: "Scooter", slug: "scooter" },
      { name: "Taşıma Çantaları", slug: "tasima-cantalari" },
      { name: "Seyahat Portbebeleri", slug: "seyahat-portbebeleri" },
      { name: "Seyahat Yatakları", slug: "seyahat-yataklari" },
      { name: "Seyahat Aksesuarları", slug: "seyahat-aksesuarlari" },
    ],
  },
  {
    name: "Tekstil",
    slug: "tekstil",
    tagline: "Yumuşacık dokular.",
    description: "Bebek tekstili, uyku ürünleri, havlu ve bornozlar, battaniyeler ve örtüler.",
    image: img("cat-textile"),
    attributes: ["color"],
    children: [
      { name: "Bebek Tekstil", slug: "bebek-tekstil", image: img("cat-textile") },
      { name: "Uyku Ürünleri", slug: "uyku-urunleri" },
      { name: "Havlu & Bornoz", slug: "havlu-bornoz" },
      { name: "Tekstil Battaniyeler", slug: "tekstil-battaniyeler" },
      { name: "Örtüler", slug: "ortuler" },
    ],
  },
];

export const BRANDS = [
  { name: "Nordlie", slug: "nordlie", description: "İskandinav tasarım anlayışıyla hafif ve dayanıklı bebek arabaları. (Demo marka)" },
  { name: "Velora", slug: "velora", description: "Şehir hayatına uygun kompakt ve ikiz bebek arabası çözümleri. (Demo marka)" },
  { name: "Mira Safe", slug: "mira-safe", description: "Güvenlik odaklı oto koltuğu ve seyahat sistemleri. (Demo marka)" },
  { name: "Lumo Baby", slug: "lumo-baby", description: "Uyku, bakım ve seyahat için akıllı bebek ürünleri. (Demo marka)" },
  { name: "Oakwood Kids", slug: "oakwood-kids", description: "Doğal ahşap ve zamansız formlarla bebek ve çocuk odası mobilyaları. (Demo marka)" },
  { name: "Petit Nido", slug: "petit-nido", description: "Organik dokular ve yumuşak renklerle bebek tekstili ve bakım ürünleri. (Demo marka)" },
  { name: "Kozy", slug: "kozy", description: "Ahşap mama sandalyeleri, oyuncaklar ve yaşam ürünleri. (Demo marka)" },
];

export const ATTRIBUTES = [
  {
    slug: "type",
    name: "Araba Tipi",
    type: "SELECT" as const,
    values: ["Travel Sistem", "Kabin Boy", "Baston", "İkiz", "Çift Yönlü"],
  },
  {
    slug: "color",
    name: "Renk",
    type: "COLOR" as const,
    values: [
      ["Bej", "#D9C7AE"],
      ["Krem", "#F1E8DA"],
      ["Adaçayı Yeşili", "#A9B8A0"],
      ["Pudra Mavi", "#BCD0DD"],
      ["Gül Kurusu", "#C9A19A"],
      ["Antrasit", "#45464A"],
      ["Beyaz", "#FFFFFF"],
      ["Doğal Ahşap", "#C9A47A"],
      ["Gri", "#B9B6B1"],
    ] as [string, string][],
  },
  { slug: "age", name: "Yaş", type: "SELECT" as const, values: ["0+ ay (Yenidoğan)", "6+ ay", "1–3 yaş", "3+ yaş", "4 yaşa kadar"] },
  { slug: "capacity", name: "Taşıma Kapasitesi", type: "SELECT" as const, values: ["15 kg'a kadar", "22 kg'a kadar", "2 × 22 kg"] },
  { slug: "weight", name: "Kg Aralığı", type: "SELECT" as const, values: ["0–13 kg", "0–18 kg", "9–18 kg", "9–36 kg", "0–36 kg", "15–36 kg"] },
  { slug: "isize", name: "i-Size", type: "BOOLEAN" as const, values: ["i-Size Uyumlu"] },
  { slug: "isofix", name: "ISOFIX", type: "BOOLEAN" as const, values: ["ISOFIX Bağlantılı"] },
  { slug: "rotation", name: "Dönüş Özelliği", type: "BOOLEAN" as const, values: ["360° Dönebilen"] },
  { slug: "set", name: "Takım / Tek Ürün", type: "SELECT" as const, values: ["Takım", "Tek Ürün"] },
  { slug: "material", name: "Materyal", type: "SELECT" as const, values: ["Masif Ahşap", "Kayın", "MDF Lake", "Kumaş & Alüminyum", "Silikon & Cam", "Pamuk & Müslin"] },
  { slug: "size", name: "Yatak Ölçüsü", type: "SELECT" as const, values: ["50×90 cm", "60×120 cm", "70×140 cm", "90×190 cm"] },
];

type SeedProduct = {
  name: string;
  sku: string;
  brand: string;
  category: string;
  extraCategories?: string[];
  images: string[];
  price?: number;
  salePrice?: number;
  showPrice?: boolean;
  stock?: "IN_STOCK" | "LOW_STOCK" | "OUT_OF_STOCK" | "PRE_ORDER" | "ASK_STORE";
  flags?: ("isNew" | "isBestSeller" | "isFeatured" | "isCampaign")[];
  short: string;
  description: string;
  specs?: [string, string][];
  dimensions?: [string, string][];
  setItems?: [string, string][];
  ageRange?: string;
  material?: string;
  tags?: string;
  attributes: Record<string, string[]>;
  variants?: [string, string][];
  kind?: "STANDARD" | "FURNITURE_SET";
};

export const PRODUCTS: SeedProduct[] = [
  {
    name: "Nordlie Aura Travel Sistem Bebek Arabası",
    sku: "BBK-NRD-1001",
    brand: "nordlie",
    category: "travel-sistem-bebek-arabalari",
    extraCategories: ["portbebeler"],
    images: ["p-travel-stroller", "hero-stroller"],
    price: 42900,
    salePrice: 39900,
    flags: ["isFeatured", "isBestSeller", "isCampaign"],
    short: "Portbebe, puset ve ana kucağı uyumlu, tek elle katlanabilen premium travel sistem.",
    description:
      "Aura, yenidoğan döneminden itibaren portbebe ile kullanılabilen, ardından çift yönlü puset oturağına dönüşen bir travel sistemdir. Alüminyum gövdesi, dört tekerlek süspansiyonu ve geniş alışveriş sepetiyle şehir içinde ve parkta rahat bir sürüş sunar.\n\nKumaş yüzeyler nefes alabilir dokudadır ve çıkarılarak temizlenebilir. Deri görünümlü itme kolu yüksekliği ayarlanabilir.",
    specs: [["Şasi", "Alüminyum"], ["Süspansiyon", "4 tekerlek"], ["Katlanma", "Tek elle, oturak takılıyken"], ["Ağırlık", "11,8 kg (şasi + oturak)"], ["Sırtlık", "Çok kademeli, tam yatar"]],
    dimensions: [["Açık ölçü", "86 × 60 × 104 cm"], ["Katlı ölçü", "70 × 60 × 32 cm"]],
    ageRange: "0 ay – 22 kg",
    material: "Alüminyum, polyester kumaş",
    tags: "travel sistem, portbebe, puset, yenidoğan",
    attributes: { type: ["Travel Sistem", "Çift Yönlü"], age: ["0+ ay (Yenidoğan)"], capacity: ["22 kg'a kadar"], color: ["Bej"], material: ["Kumaş & Alüminyum"] },
    variants: [["Kum Beji", "#D9C7AE"], ["Antrasit", "#45464A"]],
  },
  {
    name: "Nordlie Aura Kabin Boy Bebek Arabası",
    sku: "BBK-NRD-1002",
    brand: "nordlie",
    category: "kabin-boy-bebek-arabalari",
    images: ["p-cabin-stroller"],
    price: 18500,
    flags: ["isNew", "isFeatured"],
    short: "Uçak kabinine uygun katlanma ölçüsüyle 6,9 kg hafif seyahat arabası.",
    description:
      "Seyahati seven aileler için tasarlanan kompakt kabin boy bebek arabası. Tek hareketle katlanır, omuz askısıyla taşınabilir. Geniş tente ve havalandırma penceresi sıcak günlerde konfor sağlar.",
    specs: [["Ağırlık", "6,9 kg"], ["Katlanma", "Tek elle, kendi üzerinde durur"], ["Tente", "UPF 50+"], ["Fren", "Ayak freni"]],
    dimensions: [["Açık ölçü", "80 × 46 × 102 cm"], ["Katlı ölçü", "52 × 44 × 20 cm"]],
    ageRange: "6 ay – 22 kg",
    tags: "kabin boy, hafif, seyahat, uçak",
    attributes: { type: ["Kabin Boy"], age: ["6+ ay"], capacity: ["22 kg'a kadar"], color: ["Adaçayı Yeşili"] },
    variants: [["Adaçayı", "#A9B8A0"], ["Krem", "#F1E8DA"]],
  },
  {
    name: "Velora Duo İkiz Bebek Arabası",
    sku: "BBK-VLR-2001",
    brand: "velora",
    category: "ikiz-kardes-bebek-arabalari",
    images: ["p-twin-stroller"],
    price: 36750,
    flags: ["isBestSeller"],
    short: "Standart kapılardan geçebilen genişlikte yan yana ikiz bebek arabası.",
    description:
      "Duo, iki bağımsız oturağı ve ayrı ayrı ayarlanabilen sırtlıklarıyla ikizler veya yaşı yakın kardeşler için tasarlandı. 76 cm genişliği sayesinde standart kapılardan rahatça geçer.",
    specs: [["Oturak", "Bağımsız ayarlı 2 oturak"], ["Genişlik", "76 cm"], ["Ağırlık", "14,2 kg"]],
    dimensions: [["Açık ölçü", "90 × 76 × 105 cm"]],
    ageRange: "6 ay – 2 × 22 kg",
    tags: "ikiz, kardeş, çift",
    attributes: { type: ["İkiz"], age: ["6+ ay"], capacity: ["2 × 22 kg"], color: ["Antrasit"] },
  },
  {
    name: "Velora Lite Baston Bebek Arabası",
    sku: "BBK-VLR-2002",
    brand: "velora",
    category: "baston-bebek-arabalari",
    images: ["p-cabin-stroller"],
    price: 9990,
    salePrice: 8490,
    flags: ["isCampaign"],
    short: "Günlük kullanım için pratik, şemsiye katlanan baston bebek arabası.",
    description: "Hafif gövdesi ve kompakt katlanma yapısıyla kısa mesafeler ve yedek araba ihtiyacı için ideal bir baston bebek arabası.",
    specs: [["Ağırlık", "5,8 kg"], ["Katlanma", "Şemsiye tipi"]],
    ageRange: "6 ay – 15 kg",
    tags: "baston, şemsiye, hafif",
    attributes: { type: ["Baston"], age: ["6+ ay"], capacity: ["15 kg'a kadar"], color: ["Gri"] },
  },
  {
    name: "Nordlie Terra Çift Yönlü Bebek Arabası",
    sku: "BBK-NRD-1003",
    brand: "nordlie",
    category: "cift-yonlu-bebek-arabalari",
    images: ["hero-stroller", "p-travel-stroller"],
    price: 27400,
    showPrice: false,
    stock: "ASK_STORE",
    short: "Arazi tipi tekerlekler ve çift yönlü oturakla her zemine uygun.",
    description: "Terra, şişme görünümlü köpük tekerlekleri ve güçlü süspansiyonuyla park yolları ve engebeli zeminler için tasarlandı. Oturak hem anneye dönük hem yola dönük takılabilir.",
    specs: [["Tekerlek", "Patlamaz köpük, büyük çap"], ["Oturak", "Çift yönlü"]],
    ageRange: "0 ay – 22 kg",
    tags: "çift yönlü, arazi",
    attributes: { type: ["Çift Yönlü"], age: ["0+ ay (Yenidoğan)"], capacity: ["22 kg'a kadar"], color: ["Bej"] },
  },
  {
    name: "Lumo Baby Cocoon Portbebe",
    sku: "BBK-LMB-3001",
    brand: "lumo-baby",
    category: "portbebeler",
    extraCategories: ["seyahat-portbebeleri"],
    images: ["p-travel-stroller"],
    price: 6250,
    flags: ["isNew"],
    short: "Yenidoğanlar için düz yatış pozisyonu sunan, havalandırmalı portbebe.",
    description: "Cocoon, bebeğin sırtını düz pozisyonda destekleyen sert tabanlı yapısı ve nefes alan iç kumaşıyla yenidoğan dönemine uygun bir portbebedir.",
    ageRange: "0 – 6 ay",
    tags: "portbebe, yenidoğan",
    attributes: { age: ["0+ ay (Yenidoğan)"], color: ["Bej"] },
  },
  {
    name: "Mira Safe Shield 360 i-Size Oto Koltuğu 0–36 kg",
    sku: "BBK-MRS-4001",
    brand: "mira-safe",
    category: "0-36-kg-oto-koltuklari",
    extraCategories: ["i-size-oto-koltuklari"],
    images: ["p-car-seat-360", "cat-car-seat"],
    price: 21900,
    salePrice: 19750,
    flags: ["isFeatured", "isBestSeller", "isCampaign"],
    short: "360° dönebilen, ISOFIX bağlantılı, doğumdan 12 yaşa kadar kullanılan oto koltuğu.",
    description:
      "Shield 360, tek elle döndürülebilen gövdesi sayesinde bebeğinizi araca yerleştirmeyi kolaylaştırır. Yenidoğan iç minderi, ayarlanabilir baş desteği ve yan darbe koruması ile uzun yıllar kullanım sunar.",
    specs: [["Standart", "i-Size (R129)"], ["Bağlantı", "ISOFIX + destek ayağı"], ["Dönüş", "360°"], ["Yön", "0–18 kg arkaya dönük"]],
    dimensions: [["Ölçü", "44 × 59 × 66 cm"]],
    ageRange: "0 – 12 yaş (40–150 cm)",
    tags: "oto koltuğu, isofix, i-size, 360",
    attributes: { weight: ["0–36 kg"], age: ["0+ ay (Yenidoğan)"], isize: ["i-Size Uyumlu"], isofix: ["ISOFIX Bağlantılı"], rotation: ["360° Dönebilen"], color: ["Gri"] },
  },
  {
    name: "Mira Safe Nest i-Size Ana Kucağı 0–13 kg",
    sku: "BBK-MRS-4002",
    brand: "mira-safe",
    category: "0-13-kg-oto-koltuklari",
    extraCategories: ["i-size-oto-koltuklari"],
    images: ["p-infant-carrier"],
    price: 8900,
    flags: ["isNew"],
    short: "Travel sistem uyumlu, hafif ana kucağı tipi oto koltuğu.",
    description: "Nest, adaptör ile pek çok bebek arabasına takılabilen, 3,4 kg ağırlığında hafif bir ana kucağı oto koltuğudur. Geniş tente ve ergonomik taşıma kolu bulunur.",
    specs: [["Standart", "i-Size (R129)"], ["Ağırlık", "3,4 kg"]],
    ageRange: "0 – 15 ay (40–83 cm)",
    tags: "ana kucağı, oto koltuğu, yenidoğan",
    attributes: { weight: ["0–13 kg"], age: ["0+ ay (Yenidoğan)"], isize: ["i-Size Uyumlu"], color: ["Pudra Mavi"] },
  },
  {
    name: "Mira Safe Guard 9–36 kg ISOFIX Oto Koltuğu",
    sku: "BBK-MRS-4003",
    brand: "mira-safe",
    category: "9-36-kg-oto-koltuklari",
    images: ["cat-car-seat"],
    price: 12400,
    stock: "LOW_STOCK",
    short: "Büyüyen çocuklar için ayarlanabilir, ISOFIX bağlantılı oto koltuğu.",
    description: "Guard, çocuğunuzla birlikte büyüyen baş desteği ve genişleyen yan panelleri ile 9 aydan 12 yaşa kadar kullanılabilir.",
    specs: [["Bağlantı", "ISOFIX"], ["Baş desteği", "11 kademe"]],
    ageRange: "9 ay – 12 yaş",
    tags: "oto koltuğu, isofix",
    attributes: { weight: ["9–36 kg"], age: ["1–3 yaş"], isofix: ["ISOFIX Bağlantılı"], color: ["Bej"] },
  },
  {
    name: "Lumo Baby Rise Booster Yükseltici",
    sku: "BBK-LMB-3002",
    brand: "lumo-baby",
    category: "booster-yukseltici",
    images: ["cat-car-seat"],
    price: 3450,
    short: "15–36 kg arası çocuklar için sırtlıklı yükseltici.",
    description: "Rise, araç emniyet kemerinin doğru konumlanmasını sağlayan sırtlıklı bir yükselticidir.",
    ageRange: "4 – 12 yaş",
    tags: "booster, yükseltici",
    attributes: { weight: ["15–36 kg"], age: ["3+ yaş"], color: ["Antrasit"] },
  },
  {
    name: "Oakwood Kids Linnea Bebek Odası Takımı",
    sku: "BBK-OWK-5001",
    brand: "oakwood-kids",
    category: "bebek-odasi-takimlari",
    images: ["p-nursery-set-white", "hero-nursery", "p-crib"],
    price: 64900,
    flags: ["isFeatured"],
    kind: "FURNITURE_SET",
    short: "Beyaz lake ve doğal meşe detaylı; beşik, iki kapaklı dolap ve şifonyerden oluşan takım.",
    description:
      "Linnea, sade çizgileri ve sıcak ahşap detaylarıyla bebek odasına zamansız bir görünüm kazandırır. Beşik, ileride çocuk karyolasına dönüştürülebilir. Şifonyerin üst kısmı alt açma ünitesi olarak kullanılabilir.",
    setItems: [["Beşik (karyolaya dönüşebilir)", "Yatak ölçüsü 70 × 140 cm"], ["İki kapaklı dolap", "100 × 55 × 190 cm"], ["Şifonyer + alt açma", "90 × 50 × 92 cm"], ["Kitaplık", "60 × 30 × 70 cm"]],
    specs: [["Gövde", "E1 MDF, su bazlı lake boya"], ["Ayaklar", "Masif meşe"], ["Montaj", "Mağaza ekibi tarafından (bölgeye göre)"]],
    dimensions: [["Beşik dış ölçü", "76 × 146 × 90 cm"], ["Dolap", "100 × 55 × 190 cm"], ["Şifonyer", "90 × 50 × 92 cm"]],
    ageRange: "0 – 4 yaş (beşik), sonrasında karyola",
    material: "MDF Lake + Masif Meşe",
    tags: "bebek odası, takım, beşik, dolap, şifonyer",
    attributes: { set: ["Takım"], color: ["Beyaz", "Doğal Ahşap"], material: ["MDF Lake"], size: ["70×140 cm"] },
  },
  {
    name: "Oakwood Kids Salvia Bebek Odası Takımı",
    sku: "BBK-OWK-5002",
    brand: "oakwood-kids",
    category: "bebek-odasi-takimlari",
    images: ["p-nursery-set-sage", "hero-nursery"],
    price: 71500,
    showPrice: false,
    stock: "PRE_ORDER",
    flags: ["isNew", "isFeatured"],
    kind: "FURNITURE_SET",
    short: "Adaçayı yeşili lake ve doğal ahşap kulplarla sıcak, modern bebek odası.",
    description: "Salvia takımı; büyüyen beşik, şifonyer ve geniş gardıroptan oluşur. Mat lake yüzeyler kolay temizlenir, ahşap kulplar odaya doğal bir dokunuş katar.",
    setItems: [["Büyüyen beşik", "Yatak ölçüsü 70 × 140 cm"], ["Şifonyer + alt açma", "100 × 52 × 95 cm"], ["Gardırop", "105 × 58 × 195 cm"]],
    specs: [["Gövde", "E1 MDF, mat lake"], ["Kulplar", "Kayın ahşap"]],
    dimensions: [["Beşik dış ölçü", "77 × 147 × 92 cm"], ["Şifonyer", "100 × 52 × 95 cm"], ["Gardırop", "105 × 58 × 195 cm"]],
    ageRange: "0 – 4 yaş",
    material: "MDF Lake",
    tags: "bebek odası, takım, yeşil",
    attributes: { set: ["Takım"], color: ["Adaçayı Yeşili"], material: ["MDF Lake"], size: ["70×140 cm"] },
  },
  {
    name: "Oakwood Kids Fjord Masif Ahşap Beşik 70×140",
    sku: "BBK-OWK-5003",
    brand: "oakwood-kids",
    category: "besikler",
    extraCategories: ["buyuyen-besikler"],
    images: ["p-crib", "hero-nursery"],
    price: 14900,
    flags: ["isBestSeller"],
    short: "3 kademe yükseklik ayarlı, karyolaya dönüşebilen masif ahşap beşik.",
    description: "Fjord, masif kayın ağacından üretilen, yatak tabanı üç farklı yüksekliğe ayarlanabilen bir beşiktir. Yan çıtalar sökülerek çocuk karyolasına dönüştürülebilir.",
    specs: [["Malzeme", "Masif kayın"], ["Yatak tabanı", "3 kademe"]],
    dimensions: [["Dış ölçü", "76 × 146 × 88 cm"], ["Yatak ölçüsü", "70 × 140 cm"]],
    ageRange: "0 – 4 yaş",
    material: "Masif Kayın",
    tags: "beşik, ahşap, karyola",
    attributes: { set: ["Tek Ürün"], color: ["Doğal Ahşap"], material: ["Masif Ahşap"], size: ["70×140 cm"] },
  },
  {
    name: "Petit Nido Cosy Anne Yanı Beşik",
    sku: "BBK-PTN-6001",
    brand: "petit-nido",
    category: "anne-yani-besikler",
    images: ["p-bedside-crib"],
    price: 9750,
    flags: ["isNew", "isFeatured"],
    short: "Ebeveyn yatağına sabitlenebilen, fileli yan panelli anne yanı beşik.",
    description: "Cosy, gece emzirmelerini kolaylaştırmak için ebeveyn yatağının yanına sabitlenir. Fileli paneller hava sirkülasyonu ve görüş sağlar.",
    specs: [["Yükseklik ayarı", "6 kademe"], ["Panel", "Fileli, indirilebilir"]],
    dimensions: [["Yatak ölçüsü", "50 × 90 cm"]],
    ageRange: "0 – 6 ay",
    tags: "anne yanı, beşik",
    attributes: { set: ["Tek Ürün"], color: ["Doğal Ahşap", "Gri"], material: ["Kayın"], size: ["50×90 cm"] },
  },
  {
    name: "Oakwood Kids Nova Montessori Yer Yatağı",
    sku: "BBK-OWK-5004",
    brand: "oakwood-kids",
    category: "montessori-yataklar",
    images: ["p-nursery-set-white"],
    price: 11200,
    short: "Çocuğun bağımsız hareketini destekleyen, alçak çerçeveli Montessori yatak.",
    description: "Nova, çocuğun kendi başına yatağa girip çıkabilmesini sağlayan alçak yapısıyla Montessori yaklaşımına uygundur.",
    dimensions: [["Yatak ölçüsü", "90 × 190 cm"]],
    ageRange: "1 yaş +",
    material: "Masif Ahşap",
    tags: "montessori, yer yatağı",
    attributes: { set: ["Tek Ürün"], color: ["Beyaz"], material: ["Masif Ahşap"], size: ["90×190 cm"] },
  },
  {
    name: "Oakwood Kids Linnea Şifonyer",
    sku: "BBK-OWK-5005",
    brand: "oakwood-kids",
    category: "sifonyerler",
    images: ["p-nursery-set-white"],
    price: 13900,
    short: "Alt açma üniteli, üç çekmeceli şifonyer.",
    description: "Linnea koleksiyonunun şifonyeri; geniş çekmeceleri ve sökülebilir alt açma ünitesiyle uzun yıllar kullanılabilir.",
    dimensions: [["Ölçü", "90 × 50 × 92 cm"]],
    material: "MDF Lake + Masif Meşe",
    tags: "şifonyer, alt açma",
    attributes: { set: ["Tek Ürün"], color: ["Beyaz"], material: ["MDF Lake"] },
  },
  {
    name: "Lumo Baby Dream Park Beşik",
    sku: "BBK-LMB-3003",
    brand: "lumo-baby",
    category: "park-besik",
    extraCategories: ["oyun-parki", "seyahat-yataklari"],
    images: ["cat-sleep"],
    price: 5900,
    flags: ["isBestSeller"],
    short: "Katlanabilir, fileli park beşik ve oyun parkı.",
    description: "Dream, evde oyun alanı, seyahatte yatak olarak kullanılabilen katlanır park beşiktir. Taşıma çantası ile birlikte gelir.",
    dimensions: [["Ölçü", "60 × 120 cm"]],
    ageRange: "0 – 3 yaş",
    tags: "park yatak, oyun parkı",
    attributes: { age: ["0+ ay (Yenidoğan)"], color: ["Gri"] },
  },
  {
    name: "Petit Nido Müslin Uyku Seti",
    sku: "BBK-PTN-6002",
    brand: "petit-nido",
    category: "uyku-setleri",
    extraCategories: ["uyku-urunleri", "nevresim"],
    images: ["cat-textile"],
    price: 2150,
    short: "%100 pamuk müslin nevresim, battaniye ve yastık kılıfından oluşan set.",
    description: "Nefes alan müslin dokusu sayesinde dört mevsim kullanılabilen uyku seti.",
    material: "Pamuk & Müslin",
    tags: "uyku seti, müslin, nevresim",
    attributes: { color: ["Adaçayı Yeşili", "Krem"], material: ["Pamuk & Müslin"] },
  },
  {
    name: "Kozy Grow Ahşap Mama Sandalyesi",
    sku: "BBK-KZY-7001",
    brand: "kozy",
    category: "mama-sandalyeleri",
    images: ["cat-feeding"],
    price: 7900,
    salePrice: 6950,
    flags: ["isFeatured", "isBestSeller", "isCampaign"],
    short: "Çocukla birlikte büyüyen, oturak ve ayak basamağı ayarlı kayın mama sandalyesi.",
    description: "Grow, ek gıdaya geçişten itibaren kullanılabilen, oturak ve ayak basamağı yüksekliği ayarlanabilen ahşap mama sandalyesidir. Çıkarılabilir tepsi ve emniyet kemeri bulunur.",
    specs: [["Malzeme", "Masif kayın"], ["Ayar", "Oturak ve basamak ayarlı"]],
    dimensions: [["Ölçü", "46 × 54 × 80 cm"]],
    ageRange: "6 ay +",
    material: "Kayın",
    tags: "mama sandalyesi, ahşap",
    attributes: { age: ["6+ ay"], color: ["Doğal Ahşap"], material: ["Kayın"] },
  },
  {
    name: "Petit Nido Cam Biberon Seti 3'lü",
    sku: "BBK-PTN-6003",
    brand: "petit-nido",
    category: "biberon",
    images: ["p-bottles"],
    price: 1290,
    flags: ["isNew"],
    short: "Silikon kılıflı borosilikat cam biberonlar, 120/180/240 ml.",
    description: "Isıya dayanıklı borosilikat camdan üretilen, kaymaz silikon kılıflı biberon seti.",
    material: "Silikon & Cam",
    ageRange: "0 ay +",
    tags: "biberon, cam",
    attributes: { age: ["0+ ay (Yenidoğan)"], color: ["Adaçayı Yeşili", "Krem"], material: ["Silikon & Cam"] },
  },
  {
    name: "Lumo Baby Soft Silikon Emzik 2'li",
    sku: "BBK-LMB-3004",
    brand: "lumo-baby",
    category: "emzik",
    images: ["p-bottles"],
    price: 390,
    short: "Tek parça medikal silikon, ortodontik uçlu emzik.",
    description: "Tek parça yapısı sayesinde kolay temizlenen ortodontik emzik.",
    ageRange: "0 – 6 ay",
    tags: "emzik, silikon",
    attributes: { age: ["0+ ay (Yenidoğan)"], color: ["Gül Kurusu"] },
  },
  {
    name: "Lumo Baby Vision Kameralı Bebek Telsizi",
    sku: "BBK-LMB-3005",
    brand: "lumo-baby",
    category: "bebek-telsizi",
    extraCategories: ["bebek-kamerasi"],
    images: ["p-baby-monitor"],
    price: 5450,
    flags: ["isBestSeller"],
    short: "Gece görüşlü kamera ve 3,5\" ekranlı ebeveyn ünitesi.",
    description: "Vision, gece görüşü, çift yönlü konuşma ve oda sıcaklığı göstergesine sahip kameralı bebek telsizidir.",
    specs: [["Ekran", "3,5 inç"], ["Menzil", "Açık alanda 300 m"]],
    tags: "bebek telsizi, kamera",
    attributes: { color: ["Beyaz"] },
  },
  {
    name: "Petit Nido Bebek Banyo Seti",
    sku: "BBK-PTN-6004",
    brand: "petit-nido",
    category: "banyo-setleri",
    extraCategories: ["bebek-kuvetleri", "bebek-bakim-setleri"],
    images: ["cat-care-bath"],
    price: 2890,
    flags: ["isCampaign"],
    salePrice: 2490,
    short: "Ergonomik küvet, kapüşonlu havlu ve doğal sünger içeren banyo seti.",
    description: "Yenidoğan banyosunu kolaylaştıran kaymaz tabanlı küvet ve yumuşak tekstillerden oluşan set.",
    ageRange: "0 – 12 ay",
    tags: "banyo, küvet, havlu",
    attributes: { age: ["0+ ay (Yenidoğan)"], color: ["Adaçayı Yeşili", "Gül Kurusu"] },
  },
  {
    name: "Kozy Sway Ahşap Ana Kucağı",
    sku: "BBK-KZY-7002",
    brand: "kozy",
    category: "ana-kucagi",
    extraCategories: ["ev-tipi-ana-kucagi", "salincak"],
    images: ["cat-home-living"],
    price: 6750,
    flags: ["isFeatured"],
    short: "Doğal sallanma hareketli, ahşap çerçeveli ev tipi ana kucağı.",
    description: "Sway, bebeğin kendi hareketiyle hafifçe sallanan ergonomik yapısıyla günlük kullanım için tasarlandı.",
    dimensions: [["Ölçü", "44 × 78 × 56 cm"]],
    ageRange: "0 – 9 kg",
    material: "Kayın",
    tags: "ana kucağı, salıncak, ahşap",
    attributes: { age: ["0+ ay (Yenidoğan)"], color: ["Krem", "Doğal Ahşap"], material: ["Kayın"] },
  },
  {
    name: "Kozy Ahşap Gökkuşağı & Blok Seti",
    sku: "BBK-KZY-7003",
    brand: "kozy",
    category: "egitici-oyuncaklar",
    extraCategories: ["ahsap-oyuncaklar", "ilk-oyuncaklar"],
    images: ["cat-toys"],
    price: 990,
    flags: ["isNew"],
    short: "Su bazlı boyalı ahşap gökkuşağı, çıngırak ve blok seti.",
    description: "Renk, şekil ve denge algısını destekleyen, su bazlı boyalarla boyanmış ahşap oyuncak seti.",
    ageRange: "1 yaş +",
    tags: "ahşap oyuncak, montessori, eğitici",
    attributes: { age: ["1–3 yaş"], color: ["Doğal Ahşap"] },
  },
  {
    name: "Petit Nido Örgü Peluş İkili",
    sku: "BBK-PTN-6005",
    brand: "petit-nido",
    category: "pelus-oyuncaklar",
    images: ["p-plush"],
    price: 1150,
    short: "Organik pamuk ipliğinden örgü tavşan ve ayı.",
    description: "Yumuşacık organik pamuk iplikten örülmüş, bebek dostu peluş oyuncak ikilisi.",
    ageRange: "0 ay +",
    tags: "peluş, örgü",
    attributes: { age: ["0+ ay (Yenidoğan)"], color: ["Bej", "Gül Kurusu"] },
  },
  {
    name: "Kozy Wood Denge Bisikleti",
    sku: "BBK-KZY-7004",
    brand: "kozy",
    category: "bebek-bisikletleri",
    images: ["cat-outdoor"],
    price: 3250,
    flags: ["isNew", "isFeatured"],
    short: "Pedalsız, sele yüksekliği ayarlı ahşap denge bisikleti.",
    description: "Wood, çocukların denge ve koordinasyon becerilerini geliştiren hafif ahşap denge bisikletidir.",
    ageRange: "2 – 5 yaş",
    material: "Kayın",
    tags: "denge bisikleti, ahşap",
    attributes: { age: ["1–3 yaş", "3+ yaş"], color: ["Doğal Ahşap"], material: ["Kayın"] },
  },
  {
    name: "Petit Nido Örgü Bebek Battaniyesi",
    sku: "BBK-PTN-6006",
    brand: "petit-nido",
    category: "tekstil-battaniyeler",
    extraCategories: ["battaniye", "bebek-tekstil"],
    images: ["cat-textile"],
    price: 1450,
    short: "Organik pamuk örgü battaniye, 80 × 100 cm.",
    description: "Puset, beşik ve ana kucağında kullanılabilen yumuşak örgü battaniye.",
    dimensions: [["Ölçü", "80 × 100 cm"]],
    material: "Pamuk & Müslin",
    tags: "battaniye, örgü",
    attributes: { color: ["Krem", "Pudra Mavi"], material: ["Pamuk & Müslin"] },
  },
  {
    name: "Velora Travel Seyahat Yatağı",
    sku: "BBK-VLR-2003",
    brand: "velora",
    category: "seyahat-yataklari",
    images: ["cat-sleep"],
    price: 4300,
    stock: "OUT_OF_STOCK",
    short: "Saniyeler içinde kurulan, sırt çantası boyutunda seyahat yatağı.",
    description: "Hafif yapısı ve hızlı kurulumu ile tatil ve ziyaretlerde bebeğiniz için tanıdık bir uyku alanı.",
    ageRange: "0 – 3 yaş",
    tags: "seyahat yatağı, park yatak",
    attributes: { age: ["0+ ay (Yenidoğan)"], color: ["Gri"] },
  },
];

export const HERO_SLIDES = [
  {
    eyebrow: "Yeni Sezon Seçkisi",
    title: "Küçük Dünyalar İçin Büyük Konfor",
    description: "Bebeğinizin ilk günlerinden çocukluk yıllarına kadar ihtiyaç duyduğunuz seçkin ürünler Bebbek AVM'de.",
    desktopImageUrl: img("hero-nursery"),
    imageAlt: "Doğal ahşap beşik ve krem tonlarda dekore edilmiş bebek odası",
    primaryCtaLabel: "Ürünleri Keşfet",
    primaryCtaHref: "/urunler",
  },
  {
    eyebrow: "Bebek Arabaları",
    title: "Her Yolculukta Yanınızda",
    description: "Travel sistemden kabin boy modellere, yaşam tarzınıza uygun bebek arabasını birlikte seçelim.",
    desktopImageUrl: img("hero-stroller"),
    imageAlt: "Sonbahar parkında bej renkli bebek arabası",
    primaryCtaLabel: "Bebek Arabalarını İncele",
    primaryCtaHref: "/kategori/bebek-arabalari",
  },
  {
    eyebrow: "Anne & Bebek",
    title: "İlk Günlerin Huzuru",
    description: "Bakımdan uykuya, anneyi ve bebeği düşünen ürünlerle ilk günleri daha kolay hale getirin.",
    desktopImageUrl: img("hero-mother-baby"),
    imageAlt: "Kucağında yenidoğan bebeğiyle pencere kenarında oturan anne",
    primaryCtaLabel: "Anne & Bebek Ürünleri",
    primaryCtaHref: "/kategori/anne-bebek-bakim",
  },
];

export const BANNERS = [
  {
    placement: "HOME_PRIMARY" as const,
    eyebrow: "Bebek Arabaları",
    title: "Yolculuğun Her Anında Yanınızda",
    description: "Hafif, güvenli ve şık bebek arabası koleksiyonumuzu keşfedin.",
    ctaLabel: "Koleksiyonu Keşfet",
    href: "/kategori/bebek-arabalari",
    imageUrl: img("hero-stroller"),
    imageAlt: "Parkta bebek arabası",
  },
  {
    placement: "HOME_SECONDARY" as const,
    eyebrow: "Bebek Odaları",
    title: "Tatlı Rüyalar Burada Başlar",
    description: "Zamansız tasarımlı bebek odası takımlarını mağazamızda kurulu halde inceleyin.",
    ctaLabel: "Koleksiyonu Keşfet",
    href: "/kategori/bebek-odalari",
    imageUrl: img("p-nursery-set-sage"),
    imageAlt: "Adaçayı yeşili bebek odası takımı",
  },
  {
    placement: "HOME_SPLIT" as const,
    eyebrow: "Oto Koltukları",
    title: "Güvenli Yolculuklar",
    description: "i-Size ve ISOFIX uyumlu modeller.",
    ctaLabel: "İncele",
    href: "/kategori/oto-koltuklari",
    imageUrl: img("cat-car-seat"),
    imageAlt: "Araç koltuğuna takılı oto koltuğu",
  },
  {
    placement: "HOME_SPLIT" as const,
    eyebrow: "Beslenme",
    title: "Mama Saatleri Daha Keyifli",
    description: "Ahşap mama sandalyeleri ve beslenme ürünleri.",
    ctaLabel: "İncele",
    href: "/kategori/beslenme",
    imageUrl: img("cat-feeding"),
    imageAlt: "Mutfakta ahşap mama sandalyesi",
  },
  {
    placement: "MEGA_MENU" as const,
    eyebrow: "Kampanya",
    title: "Seçili ürünlerde mağaza fırsatları",
    description: "Kampanyalı ürünleri inceleyin, WhatsApp'tan bilgi alın.",
    ctaLabel: "Kampanyalar",
    href: "/kampanyalar",
    imageUrl: img("hero-mother-baby"),
    imageAlt: "Anne ve bebek",
  },
];

export const HOME_SECTIONS = [
  { key: "hero", title: null, subtitle: null },
  { key: "local-intro", title: null, subtitle: null },
  { key: "popular-categories", title: "Popüler Kategoriler", subtitle: null },
  { key: "editorial-categories", title: "İhtiyacınız Olan Her Şey", subtitle: "Bebeğinizin her dönemine eşlik eden, özenle seçilmiş kategoriler." },
  { key: "featured", title: "Minikler İçin Seçtiklerimiz", subtitle: "Mağaza ekibimizin öne çıkardığı ürünler." },
  { key: "banner-primary", title: null, subtitle: null },
  { key: "best-sellers", title: "Çok Satanlar", subtitle: "Ailelerin en çok tercih ettiği ürünler." },
  { key: "furniture-showcase", title: "Bebek Odası Koleksiyonu", subtitle: "Huzurlu, zamansız ve güvenli odalar." },
  { key: "banner-secondary", title: null, subtitle: null },
  { key: "split-banners", title: null, subtitle: null },
  { key: "new-arrivals", title: "Yeni Gelenler", subtitle: "Vitrine yeni eklenen ürünler." },
  { key: "brands", title: "Seçkin Markalar", subtitle: null },
  { key: "whatsapp-cta", title: "Doğru ürünü birlikte seçelim", subtitle: "Ürün özellikleri, stok durumu ve sipariş için uzman ekibimize WhatsApp'tan ulaşın." },
  { key: "trust", title: null, subtitle: null },
  { key: "social", title: "Bizi Instagram'da Takip Edin", subtitle: "Yeni gelen ürünler ve mağazamızdan kareler." },
];

export const PAGES = [
  {
    slug: "kvkk",
    title: "KVKK Aydınlatma Metni",
    content:
      "Bu metin taslaktır ve yayına alınmadan önce hukuk danışmanınız tarafından işletmenize göre düzenlenmelidir.\n\nBebbek AVM olarak, 6698 sayılı Kişisel Verilerin Korunması Kanunu kapsamında veri sorumlusu sıfatıyla kişisel verilerinizi işleyebiliriz. Web sitemiz üzerinden WhatsApp'a yönlendirme yapıldığında paylaştığınız bilgiler WhatsApp'ın kendi gizlilik koşullarına tabidir.\n\nVeri sorumlusunun kimliği, işleme amaçları, aktarım tarafları, toplama yöntemi ve hukuki sebebi ile ilgili kişinin hakları bu bölümde işletme bilgilerine göre detaylandırılmalıdır.",
  },
  {
    slug: "gizlilik-politikasi",
    title: "Gizlilik Politikası",
    content:
      "Bu metin taslaktır ve yayına alınmadan önce işletmenize göre düzenlenmelidir.\n\nWeb sitemiz bir ürün kataloğudur; site üzerinden ödeme alınmaz ve üyelik oluşturulmaz. Favorilere eklediğiniz ürünler yalnızca tarayıcınızda saklanır.",
  },
  {
    slug: "cerez-politikasi",
    title: "Çerez Politikası",
    content:
      "Bu metin taslaktır ve yayına alınmadan önce işletmenize göre düzenlenmelidir.\n\nSitemiz, temel işlevler için zorunlu çerezler kullanır. Analitik veya pazarlama çerezleri eklendiğinde bu metin ve onay mekanizması güncellenmelidir.",
  },
];
